# Generated by Django 5.2.2 on 2025-08-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_item_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(max_length=1000),
        ),
    ]
